server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://creeper0809.synology.me:3306/${MYSQL_DATABASE:starlight}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:Op[08090712}
  #asdfasdfasdfds
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true
API-KEY:
  UserKey: c2hVS3dhUnF0VEFjU2xkU0FPWGt2Slh6d09tQW5IS0E=
  CompanyKey : TGltQ3V1WXBtY0VaTW1taENJY0NicFB4dXdzZ25jV3g=
  UserAPI : https://1ebe585vxl.apigw.ntruss.com/custom/v1/33476/e2c0bb4b43b08b26faf01093e26742fa22d0d4abe2700fa825297dbcd4b7f35f/document/id-card
  CompanyAPI : https://1ebe585vxl.apigw.ntruss.com/custom/v1/33475/5116e9b921ac357634a337737a845c7b73a4b097c45f9b0a51b04a7cf51a6f0e/document/biz-license
  JobOfferApi: https://apis.data.go.kr/B552583/job/job_list_env
  JobOfferKey: serviceKey=x1pc42aSDv8am9Ucfx%2BPSOF8QJ2p%2BR%2F6sjJaVeS7JHoIgPuHxDFF%2FwLi1X0vZxjnr6uip4ZxSKo%2FBCqmLqvFeQ%3D%3D

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.nan.boilerplate.springboot
  swagger-ui:
    path: /api/swagger/index.html
    tagsSorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api/swagger/json
  cache:
    disabled: true

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

jwt:
  secretKey: ${JWT_SECRET:your_jwt_secret}
  issuer: ${JWT_ISSUER:https://github.com/your-github-id}
  expirationMinute: 60

swagger:
  contact-name: ${SWAGGER_CONTACT_NAME:your-name}
  contact-mail: ${SWAGGER_CONTACT_MAIL:example@example.com}
  contact-url: ${SWAGGER_CONTACT_URL:https://example.com}
  app-name: ${SWAGGER_APP_NAME:Example App}
  app-description: ${SWAGGER_APP_DESCRIPTION:Example App Description}
  app-version: ${SWAGGER_APP_VERSION:1.0.0}
  app-license-url: ${SWAGGER_APP_LICENSE_URL:https://www.apache.org/licenses/LICENSE-2.0.html}
  app-license: ${SWAGGER_APP_LICENSE:Apache 2.0}